import '/imports/api/shows/server/methods/inserts.js';
import '/imports/api/shows/server/methods/deletes.js';
import '/imports/api/shows/server/methods/updates.js';
import '/imports/api/shows/shows.js';
import '/imports/api/shows/server/publications/all_shows.js';
import '/imports/api/instagram/instagramCollection.js';
import '/imports/api/instagram/server/publications/all_insta.js';
import '/imports/api/twitter/twitterCollection.js';
import '/imports/api/twitter/server/publications/all_twitter.js';
